/**
 * Language Icon Components
 * Real programming language icons from react-icons library
 */

import { IconType } from "react-icons";

import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiRust,
  SiReact,
  SiGo,
  SiPhp,
  SiCss3,
  SiHtml5,
  SiYaml,
  SiGnubash,
  SiCplusplus,
  SiSwift,
  SiKotlin,
  SiDart,
  SiRuby,
  SiElixir,
  SiHaskell,
  SiScala,
  SiClojure,
  SiLua,
  SiPerl,
  SiR,
  SiJulia,
  SiMarkdown,
  SiDocker,
  SiVim,
  SiSqlite,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiNginx,
  SiApache,
  SiRedis,
  SiElasticsearch,
  SiSass,
  SiLess,
  SiStylus,
  SiTailwindcss,
  SiBootstrap,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiNextdotjs,
  SiNuxtdotjs,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiDjango,
  SiSpring,
  SiLaravel,
  SiRubyonrails,
  SiGraphql,
  SiPrisma,
} from "react-icons/si";

import { DiTerminal } from "react-icons/di";
import { VscJson, VscFileCode } from "react-icons/vsc";
import { FaCode } from "react-icons/fa";

type TLanguageIconMap = {
  [key: string]: IconType;
};

export const LANGUAGE_ICONS: TLanguageIconMap = {
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  java: FaCode,
  csharp: FaCode,
  "c#": FaCode,
  cpp: SiCplusplus,
  "c++": SiCplusplus,
  c: SiCplusplus,
  rust: SiRust,
  go: SiGo,
  golang: SiGo,
  swift: SiSwift,
  kotlin: SiKotlin,
  dart: SiDart,
  php: SiPhp,
  ruby: SiRuby,
  elixir: SiElixir,
  haskell: SiHaskell,
  scala: SiScala,
  clojure: SiClojure,
  lua: SiLua,
  perl: SiPerl,
  r: SiR,
  julia: SiJulia,
  matlab: FaCode,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss3,
  css3: SiCss3,
  scss: SiSass,
  sass: SiSass,
  less: SiLess,
  stylus: SiStylus,
  react: SiReact,
  jsx: SiReact,
  tsx: SiReact,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  nextjs: SiNextdotjs,
  "next.js": SiNextdotjs,
  nuxtjs: SiNuxtdotjs,
  "nuxt.js": SiNuxtdotjs,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  nodejs: SiNodedotjs,
  "node.js": SiNodedotjs,
  express: SiExpress,
  expressjs: SiExpress,
  fastapi: SiFastapi,
  flask: SiFlask,
  django: SiDjango,
  spring: SiSpring,
  springboot: SiSpring,
  laravel: SiLaravel,
  rails: SiRubyonrails,
  "ruby-on-rails": SiRubyonrails,
  json: VscJson,
  yaml: SiYaml,
  yml: SiYaml,
  xml: VscFileCode,
  sql: SiSqlite,
  sqlite: SiSqlite,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  redis: SiRedis,
  elasticsearch: SiElasticsearch,
  docker: SiDocker,
  dockerfile: SiDocker,
  nginx: SiNginx,
  apache: SiApache,
  bash: SiGnubash,
  shell: SiGnubash,
  sh: SiGnubash,
  zsh: DiTerminal,
  fish: DiTerminal,
  powershell: DiTerminal,
  ps1: DiTerminal,
  markdown: SiMarkdown,
  md: SiMarkdown,
  vim: SiVim,
  viml: SiVim,
  graphql: SiGraphql,
  gql: SiGraphql,
  prisma: SiPrisma,
  default: FaCode,
} as const;

export function getLanguageIcon(language: string): IconType {
  const normalizedLanguage = language.toLowerCase().trim();
  return LANGUAGE_ICONS[normalizedLanguage] || LANGUAGE_ICONS.default;
}
