"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.schema = exports.db = void 0;
var serverless_1 = require("@neondatabase/serverless");
var neon_serverless_1 = require("drizzle-orm/neon-serverless");
var env_1 = require("env");
var schema = require("schema");
exports.schema = schema;
var pool = new serverless_1.Pool({ connectionString: env_1.env.DATABASE_URL });
exports.db = (0, neon_serverless_1.drizzle)(pool, { schema: schema });
